# Generated by Django 3.2.4 on 2021-06-30 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_product_discountprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='Change product visibility', verbose_name='Product visibility')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.IntegerField()),
                ('discountAmount', models.IntegerField()),
                ('delivaryCost', models.IntegerField()),
                ('finalAmount', models.IntegerField()),
                ('paymentStatus', models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete')], default='incomplete', max_length=50)),
                ('paymentMethod', models.CharField(choices=[('nope', 'nope'), ('paypal', 'paypal'), ('sslcommerce', 'sslcommerce')], default='nope', max_length=50)),
                ('paymentID', models.CharField(max_length=100)),
                ('delivaryStatus', models.CharField(choices=[('picked', 'picked'), ('on the way', 'on the way'), ('delivared', 'delivared')], default='picked', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAddress', to='accounts.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeOrderdUser', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='order.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='OrderdItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='order.placeorder')),
                ('prduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productList', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addToCart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
